from __future__ import annotations

DEFAULT_COST_ARTICLES = (
    ("MAT", "direct", "Материалы и конструкции"),
    ("MAT_DELIVERY", "direct", "Доставка материалов"),
    ("MAT_WASTE", "direct", "Потери и отходы материалов"),
    ("LAB", "direct", "ФОТ рабочих начисленный"),
    ("LAB_TAX", "direct", "Страховые взносы и НДФЛ"),
    ("LAB_SHIFT", "direct", "Вахта: проезд, проживание, питание"),
    ("MACH_OWN", "direct", "Собственная техника: машино-часы"),
    ("MACH_RENT", "direct", "Арендованная техника"),
    ("MACH_FUEL", "direct", "ГСМ"),
    ("MACH_MOVE", "direct", "Перебазировка техники"),
    ("MACH_IDLE", "direct", "Простой техники"),
    ("MACH_REPAIR", "direct", "Ремонт, ТО, амортизация"),
    ("SUB", "direct", "Субподряд"),
    ("LOG", "direct", "Логистика и транспорт"),
    ("OVR_SITE", "indirect", "Накладные расходы объекта"),
    ("OVR_COMPANY", "indirect", "Накладные расходы компании"),
    ("TEMP_FAC", "indirect", "Временные здания и сооружения"),
    ("TRAFFIC", "indirect", "Организация дорожного движения"),
    ("LAB_CONTROL", "indirect", "Лабораторный контроль и геодезия"),
    ("MOB", "indirect", "Мобилизация и демобилизация"),
    ("WINTER", "indirect", "Зимнее удорожание"),
    ("DRAIN", "indirect", "Водоотлив"),
    ("INSUR", "indirect", "Страхование"),
    ("BANK_GUAR", "financial", "Банковская гарантия"),
    ("TREASURY", "financial", "Казначейское сопровождение"),
    ("FINANCE", "financial", "Финансирование кассового разрыва"),
    ("WARRANTY_RET", "financial", "Гарантийное удержание"),
    ("PENALTY_OURS", "financial", "Неустойка наша"),
    ("OTHER", "other", "Прочие затраты"),
)
